name: Stock Push Job

on:
  schedule:
    - cron: "0 3 * * 1-5"   # 台灣時間 11AM（UTC+8 = UTC 1AM）
    - cron: "0 5 * * 1-5"   # 台灣時間 1PM（UTC+8 = UTC 5AM）
  workflow_dispatch:       # 可手動觸發

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Wake up Render app
        run: curl https://stock-assistant-s63m.onrender.com

      - name: Wait for 60 seconds
        run: sleep 60

      - name: Trigger Push Notification
        run: curl -X POST https://stock-assistant-s63m.onrender.com/push_stock
